# Generated by Django 3.1.8 on 2021-04-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BauDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=25)),
                ('profileBio', models.CharField(max_length=25)),
                ('profileImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
