# Generated by Django 3.1.8 on 2021-04-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BauDB', '0006_auto_20210408_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='today_model',
        ),
    ]
