# Generated by Django 3.1.8 on 2021-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BauDB', '0010_thisweek_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='profileBio',
            field=models.TextField(),
        ),
    ]
